export default {
    SET_APP_STATE: 'SET_APP_STATE',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    ACTION_FAILED: 'ACTION_FAILED',

    SET_MODEL_FILTER: 'SET_MODEL_FILTER',
    SET_MODEL_PAGINATION: 'SET_MODEL_PAGINATION',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SET_MODEL_INSTRUCTIONS: 'SET_MODEL_INSTRUCTIONS',

    UPDATE_MODEL_RESULTS: 'UPDATE_MODEL_RESULTS',

    SET_MODEL_DETAILS: 'SET_MODEL_DETAILS',
    CLEAR_MODEL_DETAILS: 'CLEAR_MODEL_DETAILS',
    SET_MODEL_DETAILS_FAILED: 'SET_MODEL_DETAILS_FAILED',

    SHOW_NOTIFICATION_MESSAGE: 'SHOW_NOTIFICATION_MESSAGE',
    CLEAR_NOTIFICATION_MESSAGES: 'CLEAR_NOTIFICATION_MESSAGES',
    HIDE_NOTIFICATION_MESSAGE: 'HIDE_NOTIFICATION_MESSAGE',

    CERTS_UPLOADED: 'CERTS_UPLOADED',

    SET_LIMIT_BY_OPTIONS: 'SET_LIMIT_BY_OPTIONS',
};
